module.exports = GraphemeData = [
  {
    grapheme: 's',
    id: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 1,
  },
  {
    grapheme: 'a',
    id: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 28,
  },
  {
    grapheme: 't',
    id: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 4,
  },
  {
    grapheme: 'p',
    id: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 2,
  },
  {
    grapheme: 'i',
    id: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 26,
  },
  {
    grapheme: 'n',
    id: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 19,
  },
  {
    grapheme: 'm',
    id: 7,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 18,
  },
  {
    grapheme: 'd',
    id: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 5,
  },
  {
    grapheme: 'g',
    id: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 7,
  },
  {
    grapheme: 'c',
    id: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 6,
  },
  {
    grapheme: 'k',
    id: 11,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 6,
  },
  {
    grapheme: 'ck',
    id: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 6,
  },
  {
    grapheme: 'e',
    id: 13,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 27,
  },
  {
    grapheme: 'u',
    id: 14,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 30,
  },
  {
    grapheme: 'r',
    id: 15,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 22,
  },
  {
    grapheme: 'h',
    id: 16,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 17,
  },
  {
    grapheme: 'b',
    id: 17,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 3,
  },
  {
    grapheme: 'f',
    id: 18,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 10,
  },
  {
    grapheme: 'ff',
    id: 19,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 10,
  },
  {
    grapheme: 'l',
    id: 20,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 21,
  },
  {
    grapheme: 'll',
    id: 21,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 21,
  },
  {
    grapheme: 'ss',
    id: 22,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 1,
  },
  {
    grapheme: 'j',
    id: 23,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 9,
  },
  {
    grapheme: 'w',
    id: 25,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 24,
  },
  {
    grapheme: 'x',
    id: 26,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: null,
  },
  {
    grapheme: 'y',
    id: 27,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 23,
  },
  {
    grapheme: 'z',
    id: 28,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 14,
  },
  {
    grapheme: 'zz',
    id: 29,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 14,
  },
  {
    grapheme: 'ai',
    id: 30,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 33,
  },
  {
    grapheme: 'oa',
    id: 31,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 37,
  },
  {
    grapheme: 'ie',
    id: 32,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 34,
  },
  {
    grapheme: 'ee',
    id: 33,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 32,
  },
  {
    grapheme: 'or',
    id: 34,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 43,
  },
  {
    grapheme: 'ng',
    id: 35,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 20,
  },
  {
    grapheme: 'v',
    id: 36,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 11,
  },
  {
    grapheme: 'oo',
    id: 37,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 36,
  },
  {
    grapheme: 'oo',
    id: 38,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 31,
  },
  {
    grapheme: 'ch',
    id: 39,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 8,
  },
  {
    grapheme: 'sh',
    id: 40,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 15,
  },
  {
    grapheme: 'th',
    id: 41,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 12,
  },
  {
    grapheme: 'th',
    id: 42,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 13,
  },
  {
    grapheme: 'oi',
    id: 43,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 35,
  },
  {
    grapheme: 'ue',
    id: 44,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 36,
  },
  {
    grapheme: 'er',
    id: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 44,
  },
  {
    grapheme: 'ar',
    id: 46,
    createdAt: new Date(),
    updatedAt: new Date(),
    phoneme: 41,
  },
];
